
# Header
menu: #导航栏连接
  主页: /
  产品: /product
  服务: /service
  行业: /industry
  # Category: /category
  案例: /archives #/archives #归档页面URL 自定义页面标题: /自定义页面URL
  关于: /about
  加入我们: https://github.com/ltsoft

rss: /atom.xml #rss地址  默认即可

#feed:
#  type: atom       #feed 类型 (atom/rss2)
#  path: /atom.xml   #rss 路径
#  limit: 20        #在 rss 中最多生成的文章数(0显示所有)


#icon http://fontawesome.io/
#首页显示
article_index:
  -  title: 实时众源空间信息聚合平台
     content: 让中国再次和世界同步，拥抱现代浏览器。未来总会接触到移动端开发，还好移动端开发环境还不算恶劣。
     icon: icon-bolt
  -  title: 基于社交媒体时空模型的旅游景点推荐平台
     content: 让中国再次和世界同步，拥抱现代浏览器。未来总会接触到移动端开发，还好移动端开发环境还不算恶劣。
     icon: icon-bolt
  -  title: 通用地名地址检索服务平台
     content: 让中国再次和世界同步，拥抱现代浏览器。未来总会接触到移动端开发，还好移动端开发环境还不算恶劣。
     icon: icon-bolt
  -  title: 地名地址公共信息服务平台
     content: 让中国再次和世界同步，拥抱现代浏览器。未来总会接触到移动端开发，还好移动端开发环境还不算恶劣。
     icon: icon-bolt
  -  title: 地名地址数据整合发布平台
     content: 让中国再次和世界同步，拥抱现代浏览器。未来总会接触到移动端开发，还好移动端开发环境还不算恶劣。
     icon: icon-bolt
  -  title: 微信公众信息服务平台
     content: 让中国再次和世界同步，拥抱现代浏览器。未来总会接触到移动端开发，还好移动端开发环境还不算恶劣。
     icon: icon-bolt



# Content
excerpt_link: Read More  #阅读更多的文字显示
fancybox: true  #开启fancybox效果

# Miscellaneous #社交网络和统计连接地址
baidu_analytics: //hm.baidu.com/hm.js?8a307b511e2232f2e357b3e14f156b70
favicon: /css/favicon.ico
logo: /css/logo.png